version: '3.4'

services:
  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=5000
    ports:
      - "5000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  cartservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5003
    ports:
      - "5003:5003"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  productservice.db:
    container_name: productservice_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=productdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_productservice_data:/var/lib/postgresql/data2/

  cartservice.db:
    container_name: cartservice_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cartdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_cartservice_data:/var/lib/postgresql/data2/
      
  authservice.db:
    container_name: authservice_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authdb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_authservice_data:/var/lib/postgresql/data2/
        
  cartservice.db.mongo:
    container_name: cartservice_db_mongo
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_cartservice_data:/data/db
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  
  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      
  rabbitmq:    
    container_name: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
        
#  consul:
#    container_name: "consul"
#    restart: always
#    ports:
#      - '8500:8500'
#    volumes:
#      - consul-data:/consul/data