version: '3.4'

services:
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ./Services/ProductService/ProductService.API/Dockerfile

  productservice.db:
    image: postgres
    
  cartservice.db:
    image: postgres
    
volumes:
    postgres_productservice_data:
    postgres_cartservice_data: