version: '3.4'

services:
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/OcelotApiGateway/Dockerfile

  cartservice.api:
    image: ${DOCKER_REGISTRY-}cartserviceapi
    build:
      context: .
      dockerfile: Services/CartService/CartService.API/Dockerfile

  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: Services/ProductService/ProductService.API/Dockerfile

  productservice.db:
    image: postgres
  
  cartservice.db:
    image: postgres
    
  authservice.db:
    image: postgres
    
  redis:
    image: redis:latest

volumes:
  postgres_productservice_data:
  postgres_cartservice_data:
  postgres_authservice_data:
  redis-data:
    driver: local